management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info
          - beans
          - env

spring:
  config:
    import: "optional:file:.env[.properties]"
