spring:
  config:
    import:
      - optional:classpath:.env.properties
  flyway:
    baseline-on-migrate: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/campdb
    username: postgres
    password: camp
  jackson:
      accept-empty-string-as-null: true

wildfire:
  api:
    base-url: ${WILDFIRE_API_BASE}
    service-key: ${WILDFIRE_SERVICE_KEY}

logging:
  level:
    root: INFO
    org.springframework: INFO
    com.example.campingweather: INFO

