spring:
  profiles: test

  datasource:
    # H2 ??? DB ??, PostgreSQL ??? ??
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  flyway:
    # Flyway? H2? ??????
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
    user: sa
    password:
