name: backend-ci
on:
  pull_request:
    paths: ['backend/**']

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Gradle test
        working-directory: backend
        run: ./gradlew --no-daemon test

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - name: Build JAR
        working-directory: backend
        run: ./gradlew --no-daemon bootJar
      - name: Docker build
        working-directory: backend
        run: docker build -t campintel-backend:ci .
