name: Backend CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle

      # 실행권한 부여 + 빌드 ― 한 스텝
      - name: Build with Gradle
        run: |
          chmod +x backend/gradlew
          backend/gradlew clean bootJar --no-daemon

      # 헬스 체크
      - name: Health check
        run: |
          JAR=$(ls backend/build/libs/*SNAPSHOT.jar | grep -v plain | head -n1)
          java -jar "$JAR" --server.port=8080 &
          PID=$!
          sleep 30
          curl -f http://localhost:8080/actuator/health
          kill $PID
