name: Backend CI          # 워크플로 이름

on:                       # 언제 실행?
  pull_request:           # PR 올릴 때
    paths: [ 'backend/**' ]
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run: { working-directory: backend }

    steps:
      - uses: actions/checkout@v4          # 1) 코드 가져오기
      - uses: actions/setup-java@v4        # 2) JDK 21
        with:
          distribution: temurin
          java-version: '21'
          cache: gradle
      - run: ./gradlew clean build --no-daemon   # 3) 빌드·테스트
      - name: Health check                     # 4) /actuator/health
        run: |
          JAR=$(ls build/libs/*.jar | head -n1)
          java -jar "$JAR" --server.port=8080 &
          PID=$!
          sleep 25
          curl -f http://localhost:8080/actuator/health
          kill $PID
