name: backend-ci

on:
  pull_request:
    branches:
      - '**'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission to gradlew
        run: chmod +x backend/gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Gradle test
        working-directory: backend
        run: ./gradlew --no-daemon test

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v4

      - name: Grant execute permission to gradlew
        run: chmod +x backend/gradlew

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Build JAR
        working-directory: backend
        run: ./gradlew --no-daemon bootJar

      - name: Check JAR file
        working-directory: backend
        run: ls -al build/libs

      - name: Docker build
        working-directory: backend
        run: docker build -t campintel-backend:ci .
